#!/bin/bash

. "`dirname \"${0}\"`/common"

if [ -f "${BUILD_DIRECTORY}/skipDeploy" ]; then
	log INFO "Deploy will be skipped."
	exit 0
fi

include versionBased
include deploy-docker
include deploy-github-artifacts

deploy-docker
deploy-github-artifacts
